import { auth, db } from './firebase-config.js';
import { signInWithEmailAndPassword, signInAnonymously, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { doc, getDoc } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';

const $=id=>document.getElementById(id);
const normalizeId=v=>String(v||'').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'');
async function sha256(value){const bytes=new TextEncoder().encode(String(value));const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function mode(which){$('founderPanel').classList.toggle('hidden',which!=='founder');$('employeePanel').classList.toggle('hidden',which!=='employee');$('founderTab').classList.toggle('active',which==='founder');$('employeeTab').classList.toggle('active',which==='employee');}
$('founderTab')?.addEventListener('click',()=>mode('founder'));$('employeeTab')?.addEventListener('click',()=>mode('employee'));

async function founderRedirect(user){const snap=await getDoc(doc(db,'users',user.uid));if(!snap.exists())throw new Error('Founder profile was not found.');const p=snap.data();if(p.role!=='founder'||p.active!==true)throw new Error('Founder access is not active.');const session={uid:user.uid,email:user.email,name:p.name||user.email,role:'founder',businessId:p.businessId||'sandbox-media'};localStorage.setItem('sbx_session',JSON.stringify(session));sessionStorage.setItem('sbxUser',JSON.stringify(session));location.replace('./founder/index.html');}

$('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const err=$('loginError'),btn=e.currentTarget.querySelector('button');err.textContent='';try{btn.disabled=true;btn.textContent='Signing in…';const c=await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);await founderRedirect(c.user);}catch(x){console.error(x);err.textContent=x.code==='auth/invalid-credential'?'Incorrect email or password.':(x.message||'Sign in failed.');}finally{btn.disabled=false;btn.textContent='Sign in';}});

$('employeeLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();const err=$('employeeLoginError'),btn=e.currentTarget.querySelector('button');err.textContent='';try{btn.disabled=true;btn.textContent='Checking…';const employeeId=normalizeId($('employeeId').value);const pin=$('employeePin').value;if(!employeeId||pin.length<4)throw new Error('Enter a valid Employee ID and PIN.');if(!auth.currentUser||!auth.currentUser.isAnonymous){await signOut(auth).catch(()=>{});await signInAnonymously(auth);}const snap=await getDoc(doc(db,'employeeLogins',employeeId));if(!snap.exists())throw new Error('Invalid Employee ID or PIN.');const p=snap.data();if(p.active!==true)throw new Error('This employee account is disabled.');if(await sha256(pin)!==p.pinHash)throw new Error('Invalid Employee ID or PIN.');const session={uid:auth.currentUser.uid,loginDocId:employeeId,employeeId:p.employeeId||employeeId,name:p.name||employeeId,email:p.email||'',role:'employee',businessId:p.businessId||'sandbox-media',businessName:p.businessName||'Sandbox Media',department:p.department||'Unassigned',designation:p.designation||'Employee'};localStorage.setItem('sbx_session',JSON.stringify(session));sessionStorage.setItem('sbxUser',JSON.stringify(session));location.replace('./employee/index.html');}catch(x){console.error(x);err.textContent=x.code==='auth/admin-restricted-operation'?'Enable Anonymous sign-in in Firebase Authentication.':(x.message||'Employee sign in failed.');}finally{btn.disabled=false;btn.textContent='Open Employee Portal';}});

onAuthStateChanged(auth,async user=>{if(!user||user.isAnonymous)return;try{await founderRedirect(user);}catch{}});
